name: Bug Report
description: Report a bug or unexpected behavior in Na0S
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill out the fields below so we can investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug you encountered.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide the exact steps to reproduce the behavior.
      placeholder: |
        1. Import na0s: `from na0s import scan`
        2. Call scan with: `scan("...")`
        3. Observe the error or unexpected result
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: Describe what actually happened, including any error messages.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Traceback
      description: Paste any relevant log output or Python traceback. This will be rendered as code.
      render: shell
    validations:
      required: false

  - type: input
    id: na0s-version
    attributes:
      label: Na0S Version
      description: "Run `python -c \"import na0s; print(na0s.__version__)\"` to get your version."
      placeholder: "e.g., 0.3.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: "Run `python --version` to get your version."
      placeholder: "e.g., 3.11.5"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your OS and version.
      placeholder: "e.g., Ubuntu 22.04, macOS 14.2, Windows 11"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (e.g., custom configuration, integration details).
    validations:
      required: false
